# On OSX using clang, on Linux use GCC

language: cpp
sudo: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          source:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
    - os: osx
      osx_image: xcode8

script:
  - cmake .
  - cmake --build . -- -j2

notifactions:
  email:
    recipients:
      - aclaure@gmail.com
    on_suucess: never
    on_failre: always