language: cpp
sudo: false

matrix:
  include:
    - os: osx
      osx_image: xcode8.3

script:
  - cmake .
  - cmake --build . -- -j2

notifactions:
  email:
    recipients:
      - aclaure@gmail.com
    on_suucess: never
    on_failre: always