dist: trusty
sudo: false
language: cpp

os:
  - linux
    addons:
      apt:
        source:
          - ubuntu-toolchain-r-test
        packages:
          - g++-5
  - osx
    osx_image: xcode8

compiler:
  - gcc
  - clang

script:
  - cmake .
  - cmake --build . -- -j2

notifactions:
  email:
    recipients:
      - aclaure@gmail.com
    on_suucess: never
    on_failre: always